name: Prevent security misconfigurations
on: pull_request
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: config
          serverity: CRITICAL,HIGH
          exit-code: 1
