name: Static Application Security Testing
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: acrions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install bandit
      - run: bandit -r .
